apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: rethink
  name: rethink
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rethink
    spec:
      containers:
      - args:
        - rethinkdb
        - proxy
        - --bind
        - all
        - --join
        - rethink-shard
        image: rethinkdb:latest
        name: rethink
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
