apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: worker
  name: worker
spec:
  containers:
  - env:
    - name: DATABASE_HOST
      value: cion_rethink
    - name: DATABASE_PORT
      value: "28015"
    - name: ORCHESTRATOR_ADDRESS
      value: cion_orchestrator:8890
    image: cion/worker:latest
    name: worker
    resources: {}
  restartPolicy: OnFailure
status: {}
