version: "3.3"

services:
  worker:
    image: cion/worker:latest
    networks:
      - backend
      - net
    depends_on:
      - rethink
      - orchestrator
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      - ORCHESTRATOR_ADDRESS=orchestrator:8890
      - DATABASE_HOST=rethink-proxy
      - DATABASE_PORT=28015
      - LOGLEVEL=10 # DEBUG

  orchestrator:
    image: cion/orchestrator:latest
    networks:
      backend:
        aliases:
          - orchestrator
      net: {}
    environment:
      - DATABASE_HOST=rethink-proxy
      - DATABASE_PORT=28015
      - LOGLEVEL=10 # DEBUG
    depends_on:
      - rethink

  rethink-shard:
    image: rethinkdb:latest
    command: rethinkdb --bind all --no-http-admin
    networks:
      rdb-net:
        aliases:
          - rethink-shard
    volumes:
      - cion:/data
    deploy:
      placement:
        constraints: [node.role == manager]

  rethink:
    image: rethinkdb:latest
    command: rethinkdb proxy --bind all --join rethink-shard
    networks:
      rdb-net: {}
      net:
        aliases:
          - rethink-proxy

  catalyst:
    image: cion/catalyst:latest
    networks:
      - net
    environment:
      - DATABASE_HOST=rethink-proxy
      - DATABASE_PORT=28015
      - URL_TOKEN=beafa736cb4e2a7e14dadff85572b4ef64843db4a90501ade21b9dbc1a9584ce4ebeadfffe3a469c2087c1aa10dd01001b9be5378c0691cda0748f56792655a
    depends_on:
      - rethink

  api:
    image: cion/api:latest
    networks:
      net: {}
      web:
        aliases:
          - api
    environment:
      - DATABASE_HOST=rethink-proxy
      - DATABASE_PORT=28015
      - LOGLEVEL=20 # INFO
    depends_on:
      - rethink

  web:
    image: cion/web:latest
    networks:
      - web
    environment:
      - API_HOST=api
      - API_PORT=5000
    depends_on:
      - api

networks:
  net:
    external: false
  rdb-net:
    external: false
  backend:
    external: false
  web:
    external: false

volumes:
  cion:
    driver: local

---

profile: local

services:
  worker:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{CION_ROOT}/workq/workq:/lib/workq/workq"
      - "{CION_ROOT}/cion-interface/cion_interface:/lib/cion-interface/cion_interface"
      - "{CION_ROOT}/rethink-wrapper/async_rethink:/lib/async-rethink/async_rethink"
      - "{CION_ROOT}/cion-worker/src:/opt/worker"
  orchestrator:
    volumes:
      - "{CION_ROOT}/workq/workq:/lib/workq/workq"
      - "{CION_ROOT}/cion-interface/cion_interface:/lib/cion-interface/cion_interface"
      - "{CION_ROOT}/rethink-wrapper/async_rethink:/lib/async-rethink/async_rethink"
      - "{CION_ROOT}/cion-orchestrator/src:/opt/orchestrator"
  web:
    volumes:
      - "{CION_ROOT}/cion-web/lib:/var/www/html"
      - "{CION_ROOT}/cion-web/etc:/etc/caddy"
    ports:
      - 80:80
  api:
    volumes:
      - "{CION_ROOT}/rethink-wrapper/async_rethink:/lib/async-rethink/async_rethink"
      - "{CION_ROOT}/cion-api/src:/opt/api"
  catalyst:
    volumes:
      - "{CION_ROOT}/cion-catalyst/src:/opt/catalyst"
    ports:
      - 8080:80
  rethink:
    ports:
      - 9004:8080

---

profile: production

services:
  worker:
    volumes:
    secrets:
      - ca.pem
      - qa.cert.pem
      - qa.key.pem

secrets:
  ca.pem:
    file: secrets/decrypted/tls/ca.pem
  qa.cert.pem:
    file: secrets/decrypted/tls/qa/cert.pem
  qa.key.pem:
    file: secrets/decrypted/tls/qa/key.pem

---
profile: expose-rdb

services:
  rethink:
    ports:
      - 28015:28015

---
profile: rc1

services:
  worker:
    image: cion/worker:rc1
  orchestrator:
    image: cion/orchestrator:rc1