apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  clusterIP:
  ports:
  - name: api
    port: 5000
    targetPort: 5000
  selector:
    io.kompose.service: api
status:
  loadBalancer: {}
