apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: api
  name: api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: api
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: cion_rethink
        - name: DATABASE_PORT
          value: "28015"
        - name: LOGLEVEL
          value: "20"
        image: cion/api:latest
        name: api
        resources: {}
      restartPolicy: Always
status: {}
