apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: catalyst
  name: catalyst
spec:
  type: NodePort
  clusterIP:
  ports:
  - name: catalyst
    port: 8080
    targetPort: 80
    nodePort: 30005
  selector:
    io.kompose.service: catalyst
status:
  loadBalancer: {}
