apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: catalyst
  name: catalyst
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: catalyst
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: rethink
        - name: DATABASE_PORT
          value: "28015"
        - name: URL_TOKEN
          value: beafa736cb4e2a7e14dadff85572b4ef64843db4a90501ade21b9dbc1a9584ce4ebeadfffe3a469c2087c1aa10dd01001b9be5378c0691cda0748f56792655a
        image: cion/catalyst:latest
        name: catalyst
        resources: {}
      restartPolicy: Always
status: {}
