apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  clusterIP:
  ports:
  - name: orchestrator
    port: 8015
    targetPort: 0
  selector:
    io.kompose.service: orchestrator
status:
  loadBalancer: {}
