apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: orchestrator
  name: orchestrator
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: orchestrator
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: rethink
        - name: DATABASE_PORT
          value: "28015"
        image: cion/orchestrator:latest
        name: orchestrator
        resources: {}
      restartPolicy: Always
status: {}
