apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: rethink
  name: rethink
spec:
  type: NodePort
  ports:
  - name: "9004"
    port: 9004
    targetPort: 8080
  selector:
    io.kompose.service: rethink
status:
  loadBalancer: {}
